import assert from "node:assert/strict";
import test from "node:test";
import { LlmReportDraftGenerator } from "../dist/llm/llm-report-draft-generator.js";
import { StubReportDraftGenerator } from "../dist/llm/report-draft-generator.js";
import { parseSections } from "../dist/llm/llm-report-draft-generator.js";

const input = {
  reportPlan: {
    id: "plan-1",
    tenantId: "t1",
    projectId: "p1",
    reportingPeriodId: "r1",
    version: 1,
    generatedBy: "INFERRED",
    sections: [{ templateSectionId: "s1", title: "Executive Summary", required: true }],
    style: { tone: "FORMAL", language: "en", formattingRules: [] },
  },
  verifiedFindings: [
    { indicatorId: "ind-1", indicatorCode: "IND-1", value: "10", unit: "sessions", calculationMethod: "SUM", reportingPeriodId: "r1", sourceRecordIds: [], qualityFlags: [], computedAt: new Date() },
  ],
  evidencePackages: [],
  activities: [],
  indicatorUpdates: [],
  reportingProfileSnapshot: { tone: "FORMAL", language: "en", rules: [] },
  generationRunId: "run-1",
};

function fakeProvider({ text, error }) {
  return {
    name: "minimax",
    model: "MiniMax-Text-01",
    promptVersion: "1",
    async complete() {
      if (error) throw error;
      return { text: text ?? "", usage: { inputTokens: 0, outputTokens: 0 } };
    },
  };
}

test("stub generator reports usedFallback=true", async () => {
  const stub = new StubReportDraftGenerator();
  const result = await stub.generateDraft(input);
  assert.equal(result.usedFallback, true);
  assert.ok(result.sections.length > 0);
});

test("LLM generator returns usedFallback=false on valid output", async () => {
  const provider = fakeProvider({
    text: JSON.stringify({ sections: [{ title: "Executive Summary", content: "Real AI narrative." }] }),
  });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, false);
  assert.equal(result.sections[0].content, "Real AI narrative.");
});

test("LLM generator returns usedFallback=true on provider error", async () => {
  const provider = fakeProvider({ error: new Error("timeout") });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, true);
  assert.ok(result.sections.length > 0);
});

test("LLM generator returns usedFallback=true on empty response", async () => {
  const provider = fakeProvider({ text: "" });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, true);
});

test("LLM generator is lenient for prose output (no JSON wrapper) and does not fall back", async () => {
  // Strict-JSON parsing is deliberately lenient: if the LLM narrates directly
  // (MiniMax sometimes does), the entire response is taken as one narrative
  // section instead of silently falling back to the deterministic stub. This
  // matches the rewrite path's lenient behaviour and prevents a real AI draft
  // from being discarded in favour of stub tables.
  const provider = fakeProvider({ text: "not json at all, just narrative prose" });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, false);
  assert.equal(result.fallbackReason, undefined);
  assert.ok(result.sections.length > 0);
});

test("parseSections parses valid output with claims", () => {
  const sections = parseSections(
    JSON.stringify({
      sections: [{ title: "A", content: "text", claims: [{ text: "c", type: "NUMERIC", proposedSources: [] }] }],
    }),
  );
  assert.ok(sections);
  assert.equal(sections.length, 1);
  assert.equal(sections[0].claims[0].type, "NUMERIC");
});

test("parseSections falls back to narrative when LLM narrates directly (no JSON)", () => {
  const sections = parseSections(
    "Narrative text generated by the LLM as prose, not JSON.",
    [{ title: "Executive Summary" }],
  );
  assert.ok(sections);
  assert.equal(sections.length, 1);
  assert.equal(sections[0].title, "Executive Summary");
  assert.ok(sections[0].content.startsWith("Narrative text"));
});

test("LLM generator returns fallbackReason=PROVIDER_TIMEOUT on AbortError", async () => {
  const provider = fakeProvider({
    error: Object.assign(new Error("request aborted"), { name: "AbortError" }),
  });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, true);
  assert.equal(result.fallbackReason, "PROVIDER_TIMEOUT");
});

test("LLM generator returns fallbackReason=PROVIDER_MALFORMED_RESPONSE on empty JSON arrays", async () => {
  // Empty `sections` array is the only "malformed" shape that still triggers
  // a fallback — the lenient parser otherwise treats prose as a single
  // narrative section. This guards against the LLM returning empty JSON.
  const provider = fakeProvider({
    text: JSON.stringify({ sections: [] }),
  });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, true);
  assert.equal(result.fallbackReason, "PROVIDER_MALFORMED_RESPONSE");
});

test("LLM generator accepts direct prose via lenient parse and avoids fallback", async () => {
  const provider = fakeProvider({
    text: "The reporting period saw 450 beneficiaries trained across 12 sessions.",
  });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.generateDraft(input);
  assert.equal(result.usedFallback, false);
  assert.equal(result.sections.length, 1);
  assert.equal(result.sections[0].content, "The reporting period saw 450 beneficiaries trained across 12 sessions.");
});

test("LLM rewrite returns fallbackUsed=true and fallbackReason on provider error", async () => {
  const provider = fakeProvider({ error: new Error("timeout") });
  const gen = new LlmReportDraftGenerator(provider);
  const result = await gen.rewriteSection({
    sectionTitle: "Executive Summary",
    content: "source text",
    mode: "REWRITE",
    audience: "DONOR",
    sourceReferences: [],
  });
  assert.equal(result.fallbackUsed, true);
  assert.ok(result.fallbackReason);
  assert.equal(result.content.length > 0, true);
});

test("LLM rewrite preserves caveats (does not strip [Needs verification] markers)", async () => {
  // The stub generator is the deterministic fallback; ensure it preserves
  // the Phase 6 invariant: caveat markers must never be silently removed.
  const stub = new StubReportDraftGenerator();
  const result = await stub.rewriteSection({
    sectionTitle: "Activities",
    content: "We trained 50 people. [Needs verification] Security protocols followed.",
    mode: "REWRITE",
    audience: "DONOR",
    sourceReferences: [],
  });
  assert.ok(result.content.includes("[Needs verification]"));
});
