"""Deterministic artifact validators (Python mirror of TS).

Pure, side-effect-free validators that mirror
`packages/infrastructure/src/ai/artifact-validators.ts`. The worker runs these
on every response before returning; on hard fail it retries once with the
validator output appended to the user prompt, then degrades per-section.

The Python mirror is the single source of truth; the TS implementation is
generated by a build-time mirror tool (see `apps/workers/scripts/`). For the
in-repo scope, parity is verified by `test_artifact_validators.py`.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from .models import GeneratedSection, SectionDraftRequest
from .writer_contract import BANNED_PHRASES


@dataclass(frozen=True)
class ValidationResult:
    ok: bool
    issues: tuple[str, ...]


def _words(text: str) -> list[str]:
    return [w for w in re.split(r"\s+", text.strip()) if w]


def _artifacts_as_dicts(section: GeneratedSection) -> list[dict[str, Any]]:
    """Convert Pydantic Artifact objects to plain dicts for homogeneous access."""
    out: list[dict[str, Any]] = []
    for art in section.artifacts or []:
        if hasattr(art, "model_dump"):
            out.append(art.model_dump())
        elif isinstance(art, dict):
            out.append(art)
    return out


def _qa_as_dicts(section: GeneratedSection) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for item in section.qa or []:
        if hasattr(item, "model_dump"):
            out.append(item.model_dump())
        elif isinstance(item, dict):
            out.append(item)
    return out


def assert_numeric_exactness(section: GeneratedSection, verified_numbers: set[str]) -> ValidationResult:
    """Every verified number must appear verbatim in `content` or any artifact payload."""
    if not verified_numbers:
        return ValidationResult(ok=True, issues=())
    content = section.content or ""
    artifact_text = _collect_artifact_text(section)
    haystack = (content + "\n" + artifact_text).lower()
    missing = sorted(n for n in verified_numbers if n.lower() not in haystack)
    if missing:
        return ValidationResult(ok=False, issues=(f"NUMERIC_PARAPHRASE missing: {', '.join(missing)}",))
    return ValidationResult(ok=True, issues=())


def assert_table_citation(section: GeneratedSection) -> ValidationResult:
    """Every non-empty TABLE row cell must have >=1 sourceReference."""
    for art in _artifacts_as_dicts(section):
        if art.get("kind") != "TABLE":
            continue
        payload = art.get("payload") or {}
        rows = payload.get("rows") or []
        for i, row in enumerate(rows):
            refs = row.get("sourceReferences") or []
            cells = row.get("cells") or []
            non_empty = [c for c in cells if c not in (None, "")]
            if non_empty and len(refs) < 1:
                return ValidationResult(ok=False, issues=(f"TABLE row {i} missing sourceReferences",))
    return ValidationResult(ok=True, issues=())


def assert_chart_data_grounding(section: GeneratedSection, verified_numbers: set[str]) -> ValidationResult:
    """Every chart series data point must equal a verified number (when set is non-empty)."""
    if not verified_numbers:
        return ValidationResult(ok=True, issues=())
    verified_lower = {v.lower() for v in verified_numbers}
    for art in _artifacts_as_dicts(section):
        if art.get("kind") != "CHART":
            continue
        payload = art.get("payload") or {}
        for series in payload.get("series") or []:
            for j, point in enumerate(series.get("data") or []):
                if point is None or point == "":
                    continue
                if str(point).lower() not in verified_lower:
                    return ValidationResult(
                        ok=False,
                        issues=(f"CHART series '{series.get('name')}' data[{j}]={point} not in verified numbers",),
                    )
    return ValidationResult(ok=True, issues=())


def assert_mandatory_questions_answered(section: GeneratedSection, req: SectionDraftRequest) -> ValidationResult:
    questions = list(req.section.mandatoryQuestions or [])
    if not questions:
        return ValidationResult(ok=True, issues=())
    qa = _qa_as_dicts(section)
    answered = {str(item.get("question", "")).strip().lower() for item in qa if isinstance(item, dict)}
    missing = [q for q in questions if q.strip().lower() not in answered]
    if missing:
        return ValidationResult(ok=False, issues=(f"MISSING_QA: {', '.join(missing)}",))
    for i, item in enumerate(qa):
        if isinstance(item, dict) and not item.get("sourceReferences"):
            return ValidationResult(ok=False, issues=(f"QA[{i}] missing sourceReferences",))
    return ValidationResult(ok=True, issues=())


def assert_delta_from_prior(
    section: GeneratedSection,
    prior_narrative_present: bool,
) -> ValidationResult:
    if not prior_narrative_present:
        return ValidationResult(ok=True, issues=())
    if section.deltaFromPrior is None:
        return ValidationResult(ok=False, issues=("MISSING_DELTA: deltaFromPrior is required when prior narrative exists",))
    return ValidationResult(ok=True, issues=())


def assert_word_count(section: GeneratedSection, req: SectionDraftRequest) -> ValidationResult:
    content = section.content or ""
    count = len(_words(content))
    issues: list[str] = []
    if req.section.minWords is not None and count < req.section.minWords:
        issues.append(f"WORD_LIMIT: {count} words < minWords={req.section.minWords}")
    if req.section.maxWords is not None and count > req.section.maxWords:
        issues.append(f"WORD_LIMIT: {count} words > maxWords={req.section.maxWords}")
    return ValidationResult(ok=not issues, issues=tuple(issues))


def assert_repetition(section: GeneratedSection, prior_summary: list[str] | None) -> ValidationResult:
    """No sentence may share >=70% token overlap with any prior_summary sentence."""
    if not prior_summary:
        return ValidationResult(ok=True, issues=())
    new_sents = re.split(r"(?<=[.!?])\s+", (section.content or "").strip())
    new_sents = [s for s in new_sents if s]
    prior_sents: list[str] = []
    for blob in prior_summary:
        prior_sents.extend(re.split(r"(?<=[.!?])\s+", str(blob).strip()))
    prior_sents = [s for s in prior_sents if s]
    if not (new_sents and prior_sents):
        return ValidationResult(ok=True, issues=())
    for ns in new_sents:
        ns_tokens = set(_normalise_tokens(ns))
        for ps in prior_sents:
            ps_tokens = set(_normalise_tokens(ps))
            if not ps_tokens:
                continue
            overlap = len(ns_tokens & ps_tokens) / max(1, len(ns_tokens | ps_tokens))
            if overlap >= 0.7:
                return ValidationResult(ok=False, issues=("DUPLICATE: sentence overlaps prior section",))
    return ValidationResult(ok=True, issues=())


def assert_banned_phrases(section: GeneratedSection) -> ValidationResult:
    haystack = (section.content or "").lower()
    hits = [p for p in BANNED_PHRASES if p.lower() in haystack]
    if hits:
        return ValidationResult(ok=False, issues=(f"BANNED_PHRASE: {', '.join(hits)}",))
    return ValidationResult(ok=True, issues=())


def assert_artifact_ordering(section: GeneratedSection) -> ValidationResult:
    """Ordinals strictly increasing, no gaps > 1."""
    ordinals = [int(art.get("ordinal", 0)) for art in _artifacts_as_dicts(section)]
    for prev, curr in zip(ordinals, ordinals[1:]):
        if curr <= prev:
            return ValidationResult(ok=False, issues=(f"ARTIFACT_ORDER: ordinal not strictly increasing ({prev}->{curr})",))
        if curr - prev > 1:
            return ValidationResult(ok=False, issues=(f"ARTIFACT_ORDER: ordinal gap > 1 ({prev}->{curr})",))
    return ValidationResult(ok=True, issues=())


def run_all(
    section: GeneratedSection,
    req: SectionDraftRequest,
    *,
    verified_numbers: set[str] | None = None,
    prior_narrative_present: bool = False,
) -> ValidationResult:
    """Run every hard validator and aggregate issues."""
    verified_numbers = verified_numbers or set()
    results = [
        assert_numeric_exactness(section, verified_numbers),
        assert_table_citation(section),
        assert_chart_data_grounding(section, verified_numbers),
        assert_mandatory_questions_answered(section, req),
        assert_delta_from_prior(section, prior_narrative_present),
        assert_word_count(section, req),
        assert_repetition(section, list(req.section.priorSectionsSummary or [])),
        assert_banned_phrases(section),
        assert_artifact_ordering(section),
    ]
    issues: list[str] = []
    for r in results:
        issues.extend(r.issues)
    return ValidationResult(ok=not issues, issues=tuple(issues))


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _normalise_tokens(text: str) -> list[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


def _collect_artifact_text(section: GeneratedSection) -> str:
    """Flatten every artifact payload into a single lowercased text blob for numeric search."""
    bits: list[str] = []
    for art in _artifacts_as_dicts(section):
        payload = art.get("payload") or {}
        kind = art.get("kind")
        if kind == "TABLE":
            for row in payload.get("rows") or []:
                bits.extend(str(c) for c in (row.get("cells") or []) if c is not None)
        elif kind == "CHART":
            bits.extend(str(c) for c in (payload.get("categories") or []))
            for series in payload.get("series") or []:
                bits.extend(str(d) for d in (series.get("data") or []) if d is not None)
        elif kind == "LIST":
            for item in payload.get("items") or []:
                if isinstance(item, dict):
                    bits.append(str(item.get("text") or ""))
        elif kind == "KEY_VALUE":
            for entry in payload.get("entries") or []:
                if isinstance(entry, dict):
                    bits.append(str(entry.get("value") or ""))
        elif kind == "QA":
            bits.append(str(payload.get("answer") or ""))
        elif kind == "DELTA":
            bits.append(str(payload.get("fromValue") or ""))
            bits.append(str(payload.get("toValue") or ""))
    return "\n".join(bits)
