"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { TOUR_STEPS } from "../domain/tour-steps";
import shotsManifest from "../domain/tour-shots.json";

type Rect = { x: number; y: number; w: number; h: number };
const SHOTS = shotsManifest.shots as Record<string, Rect | null>;
const ASPECT = `${shotsManifest.width} / ${shotsManifest.height}`;

/**
 * Public, no-signup walkthrough for the marketing hero. Reuses the Academy
 * step copy (single source of truth) and shows a real screenshot of the portal
 * behind each step, with the same spotlight the in-app tour draws. Screenshots
 * and spotlight rects are generated by `apps/web/scripts/capture-tour.mjs`.
 */
export function PublicTour() {
  const [index, setIndex] = useState(0);
  const step = TOUR_STEPS[index]!;
  const last = index === TOUR_STEPS.length - 1;
  const rect = SHOTS[step.id] ?? null;

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") setIndex((i) => Math.min(i + 1, TOUR_STEPS.length - 1));
      if (e.key === "ArrowLeft") setIndex((i) => Math.max(i - 1, 0));
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  // Card sits opposite the spotlight so it never covers what it describes.
  const cardOnRight = !rect || rect.x + rect.w / 2 < 0.5;
  const cardBottom = rect ? rect.y + rect.h / 2 < 0.5 : false;

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white">
      <div className="mx-auto max-w-6xl">
        <div className="flex items-center justify-between">
          <Link href="/" className="text-sm text-slate-400 hover:text-white">← Back to home</Link>
          <Link href="/signup" className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold hover:bg-emerald-400">Start free</Link>
        </div>
        <h1 className="mt-6 text-2xl font-bold sm:text-3xl">DonorDesk product tour</h1>
        <p className="mt-1 text-slate-400">A real walkthrough of the reporting workflow, end to end. No account needed.</p>

        <div className="mt-6 overflow-hidden rounded-xl border border-white/10 bg-slate-900 shadow-2xl">
          <div className="flex items-center gap-2 border-b border-white/10 bg-slate-800 px-4 py-2">
            <span className="h-3 w-3 rounded-full bg-red-400/80" /><span className="h-3 w-3 rounded-full bg-amber-400/80" /><span className="h-3 w-3 rounded-full bg-emerald-400/80" />
            <span className="ml-3 truncate rounded-md bg-slate-900 px-3 py-0.5 text-xs text-slate-400">donordesk.online{step.route.replace("{projectId}", "…").replace("{periodId}", "…")}</span>
          </div>
          <div className="relative w-full overflow-hidden bg-white" style={{ aspectRatio: ASPECT }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img key={step.id} src={`/tour/${step.id}.jpg`} alt={`DonorDesk screen: ${step.title}`} className="absolute inset-0 h-full w-full object-cover" />
            {rect ? (
              <div
                aria-hidden
                className="pointer-events-none absolute rounded-lg ring-2 ring-emerald-400 transition-all duration-300"
                style={{ left: `${rect.x * 100}%`, top: `${rect.y * 100}%`, width: `${rect.w * 100}%`, height: `${rect.h * 100}%`, boxShadow: "0 0 0 9999px rgba(2,6,23,0.55)" }}
              />
            ) : (
              <div aria-hidden className="pointer-events-none absolute inset-0 bg-slate-950/25" />
            )}
            <section
              className={`absolute hidden w-80 rounded-2xl border border-white/10 bg-slate-950/95 p-5 shadow-2xl backdrop-blur sm:block ${cardOnRight ? "right-4" : "left-4"} ${cardBottom ? "bottom-4" : "top-4"}`}
            >
              <StepCard index={index} last={last} onBack={() => setIndex(index - 1)} onNext={() => setIndex(index + 1)} />
            </section>
          </div>
        </div>

        <section className="mt-4 rounded-2xl border border-white/10 bg-slate-950 p-5 sm:hidden">
          <StepCard index={index} last={last} onBack={() => setIndex(index - 1)} onNext={() => setIndex(index + 1)} />
        </section>

        <nav aria-label="Tour steps" className="mt-5 flex flex-wrap justify-center gap-2">
          {TOUR_STEPS.map((s, i) => (
            <button key={s.id} type="button" onClick={() => setIndex(i)} aria-label={`Step ${i + 1}: ${s.title}`} aria-current={i === index}
              className={`h-2.5 rounded-full transition-all ${i === index ? "w-8 bg-emerald-400" : "w-2.5 bg-white/25 hover:bg-white/50"}`} />
          ))}
        </nav>
        <p className="mt-6 text-center text-sm text-slate-500">Ready to try it? <Link href="/signup" className="text-emerald-400 hover:underline">Create a free workspace</Link> — it includes a sample project with the full guided tour.</p>
      </div>
    </main>
  );
}

function StepCard({ index, last, onBack, onNext }: { index: number; last: boolean; onBack: () => void; onNext: () => void }) {
  const step = TOUR_STEPS[index]!;
  return (
    <>
      <p className="text-xs font-semibold uppercase tracking-wide text-emerald-400">Step {index + 1} of {TOUR_STEPS.length}</p>
      <h2 className="mt-1 text-lg font-semibold">{step.title}</h2>
      <p className="mt-2 text-sm text-slate-300">{step.body}</p>
      {step.rule && (
        <div className="mt-2 rounded-md bg-white/10 p-2 text-xs text-slate-200">
          <p className="font-semibold">Good to know: {step.rule.title}</p>
          <p className="mt-0.5">{step.rule.body}</p>
        </div>
      )}
      <div className="mt-4 flex items-center justify-between gap-3">
        <button type="button" disabled={index === 0} onClick={onBack} className="rounded-lg border border-white/15 px-3 py-1.5 text-sm disabled:opacity-40">Back</button>
        {last ? (
          <Link href="/signup" className="rounded-lg bg-emerald-500 px-4 py-1.5 text-sm font-semibold hover:bg-emerald-400">Start free</Link>
        ) : (
          <button type="button" onClick={onNext} className="rounded-lg bg-emerald-500 px-4 py-1.5 text-sm font-semibold hover:bg-emerald-400">Next</button>
        )}
      </div>
    </>
  );
}
