/**
 * Structured verification reasons. Gate decisions and approval/submission
 * logic must consume these enums, never infer meaning from human-readable
 * detail strings. Human-readable detail is presentation only.
 */
export type VerificationReasonCode =
  | "SOURCE_MISSING"
  | "SOURCE_NOT_FOUND"
  | "CHUNK_NOT_FOUND"
  | "SOURCE_TEXT_MISMATCH"
  | "EVIDENCE_HASH_MISMATCH"
  | "EVIDENCE_UNVERIFIED"
  | "CONFIDENTIALITY_RESTRICTED"
  | "VALUE_MISMATCH"
  | "UNIT_MISMATCH"
  | "PERIOD_MISMATCH"
  | "ENTITY_MISMATCH"
  | "DERIVATION_INVALID"
  | "ENTAILMENT_FAILED"
  | "ENTAILMENT_UNCERTAIN"
  | "CAUSAL_REVIEW_REQUIRED"
  | "COVERAGE_GAP"
  | "REQUIREMENT_UNSATISFIED";

export const VERIFICATION_REASON_CODES: VerificationReasonCode[] = [
  "SOURCE_MISSING",
  "SOURCE_NOT_FOUND",
  "CHUNK_NOT_FOUND",
  "SOURCE_TEXT_MISMATCH",
  "EVIDENCE_HASH_MISMATCH",
  "EVIDENCE_UNVERIFIED",
  "CONFIDENTIALITY_RESTRICTED",
  "VALUE_MISMATCH",
  "UNIT_MISMATCH",
  "PERIOD_MISMATCH",
  "ENTITY_MISMATCH",
  "DERIVATION_INVALID",
  "ENTAILMENT_FAILED",
  "ENTAILMENT_UNCERTAIN",
  "CAUSAL_REVIEW_REQUIRED",
  "COVERAGE_GAP",
  "REQUIREMENT_UNSATISFIED",
];

/**
 * Whether a reason code represents a deterministic failure (safe to surface as
 * a blocking verification result) or an uncertain state requiring review.
 */
export type ReasonClass = "DETERMINISTIC_FAILURE" | "UNCERTAIN" | "INTEGRITY" | "POLICY";

export const REASON_CLASSES: Record<VerificationReasonCode, ReasonClass> = {
  SOURCE_MISSING: "DETERMINISTIC_FAILURE",
  SOURCE_NOT_FOUND: "INTEGRITY",
  CHUNK_NOT_FOUND: "INTEGRITY",
  SOURCE_TEXT_MISMATCH: "INTEGRITY",
  EVIDENCE_HASH_MISMATCH: "INTEGRITY",
  EVIDENCE_UNVERIFIED: "DETERMINISTIC_FAILURE",
  CONFIDENTIALITY_RESTRICTED: "POLICY",
  VALUE_MISMATCH: "DETERMINISTIC_FAILURE",
  UNIT_MISMATCH: "DETERMINISTIC_FAILURE",
  PERIOD_MISMATCH: "DETERMINISTIC_FAILURE",
  ENTITY_MISMATCH: "DETERMINISTIC_FAILURE",
  DERIVATION_INVALID: "DETERMINISTIC_FAILURE",
  ENTAILMENT_FAILED: "DETERMINISTIC_FAILURE",
  ENTAILMENT_UNCERTAIN: "UNCERTAIN",
  CAUSAL_REVIEW_REQUIRED: "UNCERTAIN",
  COVERAGE_GAP: "DETERMINISTIC_FAILURE",
  REQUIREMENT_UNSATISFIED: "DETERMINISTIC_FAILURE",
};

export function isVerificationReasonCode(value: string): value is VerificationReasonCode {
  return (VERIFICATION_REASON_CODES as readonly string[]).includes(value);
}
