"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { listSectionRevisionsAction, type SectionRevision } from "@/lib/actions/reporting";
import { formatDateTime } from "@/lib/shared/dates";

const ORIGIN_LABEL: Record<string, string> = {
  GENERATION: "Written by the AI",
  REGENERATION: "Regenerated by the AI",
  REWRITE: "Rewritten with AI",
  MANUAL_EDIT: "Edited",
  AUTO_FIX: "Number corrected from evidence",
  RESTORE: "Earlier version restored",
  MERGE: "Merged",
};

const PREVIEW_CHARS = 180;

/**
 * The section's history (Report Editor U11/U27): every saved version, newest
 * first, with "Restore" — restoring saves that text as a new version, so
 * nothing is ever lost.
 */
export function HistoryTab({
  sectionId,
  refreshKey,
  canRestore,
  restoringId,
  onRestore,
}: {
  sectionId: string;
  /** Changes whenever the section is saved, so the list reloads. */
  refreshKey: string;
  canRestore: boolean;
  restoringId: string | null;
  onRestore: (revision: SectionRevision) => void;
}) {
  const [items, setItems] = useState<SectionRevision[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    void listSectionRevisionsAction(sectionId).then((r) => {
      if (cancelled) return;
      if (r.ok) setItems(r.value.items);
      else setError(r.error.message);
    });
    return () => {
      cancelled = true;
    };
  }, [sectionId, refreshKey]);

  if (error) return <p role="alert" className="text-sm text-danger-700 dark:text-danger-400">{error}</p>;
  if (!items) return <p className="text-sm text-slate-500 dark:text-slate-400" aria-busy="true">Loading history…</p>;
  if (items.length === 0) return <p className="text-sm text-slate-600 dark:text-slate-300">This section has no saved versions yet.</p>;

  return (
    <ol className="space-y-2.5">
      {items.map((rev) => {
        const text = rev.content.replace(/[#*`>|]/g, "").replace(/\s+/g, " ").trim();
        return (
          <li key={rev.id} className="rounded-lg border border-slate-200 p-3 text-sm dark:border-white/10">
            <div className="flex items-baseline justify-between gap-2">
              <p className="font-medium">
                Version {rev.revisionNumber}
                {rev.isCurrent && <span className="ml-1.5 text-xs font-normal text-success-700 dark:text-success-400">· current</span>}
              </p>
              <time className="shrink-0 text-xs text-slate-500 dark:text-slate-400" dateTime={rev.createdAt}>
                {formatDateTime(rev.createdAt)}
              </time>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400">{ORIGIN_LABEL[rev.changeOrigin] ?? "Saved"}</p>
            <p className="mt-1.5 line-clamp-3 text-slate-700 dark:text-slate-200">
              {text ? (text.length > PREVIEW_CHARS ? `${text.slice(0, PREVIEW_CHARS)}…` : text) : <em className="text-slate-400">Empty</em>}
            </p>
            {!rev.isCurrent && canRestore && (
              <Button size="sm" variant="secondary" className="mt-2" pending={restoringId === rev.id} disabled={restoringId !== null} onClick={() => onRestore(rev)}>
                Restore this version
              </Button>
            )}
          </li>
        );
      })}
    </ol>
  );
}
