import { attach, BASE } from "./lib.mjs"; import { writeFileSync } from "node:fs";
const { page, browser } = await attach();
await page.goto(BASE + "/projects/new"); await page.waitForLoadState("networkidle");
const sf = page.getByRole("button", { name: /start fresh/i }); if (await sf.count()) await sf.click();
await page.fill("#title", "[DEMO] Safe Water & Sanitation for Flood-Affected Communities");
await page.fill("#projectCode", "WASH-DDU-" + Date.now().toString(36).toUpperCase());
await page.fill("#donorName", "Global Water & Health Fund");
await page.fill("#implementingOrganization", "GEC");
await page.fill("#partnerOrganization", "Sindh Rural Support Network");
await page.getByRole("button", { name: "Next" }).click();
await page.fill("#country", "Pakistan"); await page.fill("#region", "Sindh"); await page.fill("#district", "Dadu");
await page.selectOption("#sector", { label: "Water, sanitation & hygiene" });
await page.fill("#startDate", "2026-03-01"); await page.fill("#endDate", "2026-08-31");
await page.getByRole("button", { name: "Next" }).click();
await page.selectOption("#reportingFrequency", { label: "Monthly" });
await page.fill("#budgetAmount", "480000"); await page.fill("#budgetCurrency", "USD");
await page.fill("#primaryContactName", "Amina Khoso");
await page.fill("#description", "Six-month emergency-to-recovery WASH project: rehabilitate safe water points, build household and school latrines, promote hygiene and strengthen water-user committees in flood-affected union councils of Dadu district.");
await page.getByRole("button", { name: "Create project" }).click();
await page.waitForURL(/\/projects\/[0-9a-f-]{36}\/setup/, { timeout: 40000 });
const P = page.url().match(/projects\/([0-9a-f-]{36})/)[1]; writeFileSync("pid3.txt", P); console.log("PROJECT", P);
await page.getByRole("button", { name: "Activate project" }).click(); await page.waitForTimeout(2500);
await page.goto(`${BASE}/projects/${P}/logframe/import`); await page.waitForLoadState("networkidle");
const { dump } = await import("./lib.mjs"); console.log((await dump(page)).join("\n")); console.log((await page.locator("main").innerText()).slice(0,1500));
await browser.close(); process.exit(0);
