export const STORY = [
 ["Two flood-damaged hand pumps at Johi were restored, and 900 people regained access to safe water; the first water user committee was formed.", "Materials for latrine construction arrived late, so latrine construction started slowly with only 20 completed.", "Water points were close to plan; latrines were below plan because of the delayed materials.", "Construction sequencing was changed to prioritise water points while materials were procured.", "A village elder volunteered his compound as the first handwashing demonstration site."],
 ["Four hand pumps and one solar mini-scheme were rehabilitated, serving 1,800 more people; chlorination started at every site.", "Road washouts near Mehar delayed two deliveries by three days.", "Water points exceeded the monthly plan thanks to a second repair team; latrines recovered to 45.", "A second repair team was hired for six weeks to catch up.", "Women on the Johi committee took over weekly chlorine dosing records."],
 ["Five water points were handed over and 2,400 people were reached with hygiene promotion, the strongest month so far.", "Flooding at one site delayed a water point by a week, and spare solar controllers were not available locally.", "Hygiene reach was above plan because schools reopened after the floods.", "Hygiene sessions were moved to school hours to reach children.", "A school girl led a handwashing song that was adopted by three schools."],
 ["Five water points were handed over, two school WASH blocks were completed and chlorine compliance reached 78 percent.", "Extreme heat reduced turnout at afternoon hygiene sessions.", "Latrine construction stayed on plan at 60 per month; school blocks were ahead of plan.", "Hygiene sessions moved to early morning because of the heat.", "Committee members now test chlorine residuals themselves with supervision."],
 ["Chlorine compliance reached 84 percent and four water points were completed; a second school block was handed over.", "A delayed delivery of spare parts held one water point for ten days.", "Water quality moved close to the 90 percent target as dosing became routine.", "Spare parts were bought locally in Dadu city to avoid further delay.", "One committee started collecting small monthly user fees for pump maintenance."],
,
 ["All eight remaining water points and the final school WASH block were completed; chlorine compliance reached 91 percent, above the 90 percent target.", "End-of-project handover meetings coincided with school exams, which limited availability of head teachers.", "Water quality, school blocks and hygiene reach finished at or above target; people with safe water reached 14,000.", "Handover sessions replaced new construction in the final weeks.", "All 12 water user committees now keep dosing and maintenance records without project support."],
];
