import { MONTHS, MON, LAST, val, split, FEM } from "./data.mjs";
const SITES = [
 ["Kanamkemer Health Centre","Nakwamekwi Dispensary","Lodwar Sub-County Hospital"],
 ["Kalokol Health Centre","Lowarengak Dispensary","Kerio Health Centre"],
 ["Katilu Health Centre","Lokori Health Centre","Lodwar Sub-County Hospital"],
 ["Lokichar Health Centre","Kainuk Dispensary","Kanamkemer Health Centre"],
 ["Lorugum Health Centre","Napuu Dispensary","Katilu Health Centre"],
 ["Kalokol Health Centre","Lokichar Health Centre","Lodwar Sub-County Hospital"]];
const day = (m, d) => `${MON[m]}-${String(Math.min(d, LAST[m])).padStart(2, "0")}`;
const CH = { // month-specific challenge / adaptation text
 1: ["Recruitment of the nurse mentors and the first procurement round took longer than planned; services at supported facilities were only partly covered in the first weeks.", "Start-up: facility baseline assessments done in all 14 facilities; mentors deployed from the second week."],
 2: ["Long-rains flooding on the Turkwel and Kerio rivers cut the Kalokol and Lowarengak roads for nine days; two outreach sites were not reached and a national Penta vaccine stock shortage lasted one week.", "Outreach routes were re-planned around the flooded roads and children missed during the stock-out were recalled in the following weeks."],
 3: ["A county nurses' industrial action lasted twelve days and reduced routine clinic hours at five facilities.", "Project-supported clinical officers ran mobile antenatal and immunization clinics at the affected facilities."],
 4: ["Solar refrigerators failed at two facilities and cattle-raid insecurity near Lorugum suspended outreach for a week.", "Vaccines were temporarily moved to the nearest working cold chain and the two refrigerators were repaired within eight days; outreach resumed with a police escort arranged by the sub-county commander."],
 5: ["Drought deepened across Turkana South and malnutrition screening numbers rose sharply; some caregivers walked long distances to reach screening points.", "CHV screening days were moved to water points and market days, and referral transport for SAM cases was organised with the county."],
 6: ["Handover of the project's solar fridges and registers to the county needed more signatures than expected, and the final KAP survey fell in a week of hot weather with low turnout in two villages.", "The sub-county health management team signed the asset handover certificates and the two villages were revisited."]};
export function activities(m) {
  const M = MONTHS[m], s = SITES[m], v = c => val(c, m);
  const [hf, hm] = split(v("HL-1.1a"), FEM["HL-1.1a"]);
  const [cf, cm] = split(v("HL-2.1a"), FEM["HL-2.1a"]);
  const [rf, rm] = split(v("HL-2.2a"), FEM["HL-2.2a"]);
  const [mf, mm] = split(v("HL-2.3a"), FEM["HL-2.3a"]);
  const [df, dm] = split(v("HL-1.4a"), FEM["HL-1.4a"]);
  const [ch, la] = CH[m + 1] ?? CH[1];
  const fac = v("HL-1.2a");
  return [
   { node: "A1.1", title: `A1.1 — EmONC, IMCI and newborn care training and mentorship, ${M} (${s[0]})`, date: day(m, 9), loc: `${s[0]}, Turkana County`, total: v("HL-1.1a"), male: hm, female: hf,
     summary: `Project clinical trainers and nurse mentors trained ${v("HL-1.1a")} health workers from supported facilities in emergency obstetric and newborn care, IMCI and essential newborn care in ${M}, and made ${v("HL-1.1b")} on-site mentorship visits to the 14 facilities.`,
     achievements: `${v("HL-1.1a")} health workers trained (${hf} female, ${hm} male) and ${v("HL-1.1b")} mentorship visits completed in ${M}.`, challenges: ch, lessons: "On-site mentorship after classroom training improves use of partographs and neonatal resuscitation.", next: m < 5 ? "Continue training cohorts and monthly mentorship visits." : "Complete the final cohort and hand mentorship tools to the sub-county health management team." },
   { node: "A1.2", title: fac ? `A1.2 — MNCH equipment kits delivered to ${fac} facilit${fac === 1 ? "y" : "ies"}, ${M}` : `A1.2 — Equipment needs assessment and procurement, ${M}`, date: day(m, 14), loc: `${s[1]}, Turkana County`, total: undefined,
     summary: fac ? `The logistics team delivered and installed essential MNCH equipment kits (delivery sets, neonatal resuscitation equipment, weighing scales, fetal dopplers and solar refrigerators where needed) at ${fac} health facilities in ${M}, with handover certificates signed by the facility in-charges.` : `A joint facility needs assessment was completed with the county pharmacist and the first equipment tender was issued; no kits were delivered in ${M}.`,
     achievements: fac ? `${fac} facilities received and signed for the full MNCH equipment kit in ${M}.` : "Needs assessment completed for 14 facilities and the tender for the first kits issued; no facilities equipped yet.", challenges: fac ? "Some items arrived in partial shipments from Nairobi because of delays on the Kitale road." : "Procurement approvals under USAID rules required three quotations and took three weeks.", lessons: "Pre-agreed kit lists with the county pharmacist avoid duplicate supplies.", next: m < 5 ? "Deliver the next batch of kits to the remaining facilities." : "Confirm equipment inventories with the county at handover." },
   { node: "A1.3", title: `A1.3 — Antenatal care, skilled delivery and transport vouchers, ${M} (${s[2]})`, date: day(m, 18), loc: `${s[2]}, Turkana County`, total: v("HL-1.3a"),
     summary: `Supported facilities recorded ${v("HL-1.3a")} first antenatal visits and ${v("HL-1.3b")} deliveries attended by skilled birth attendants in ${M}; ${v("HL-1.3c")} women were referred for emergency obstetric care using the transport voucher scheme. ANC4+ coverage reached ${v("HL-OC1a")} percent and skilled delivery ${v("HL-OC1b")} percent.`,
     achievements: `${v("HL-1.3a")} first ANC visits, ${v("HL-1.3b")} skilled deliveries and ${v("HL-1.3c")} voucher referrals in ${M}; ANC4+ ${v("HL-OC1a")} percent, skilled delivery ${v("HL-OC1b")} percent.`, challenges: ch, lessons: "Linking CHV pregnancy registers to facility ANC registers helps women return for the fourth visit.", next: m < 5 ? "Continue outreach ANC clinics and voucher reimbursements to transporters." : "Hand over voucher register and transporter agreements to the county." },
   { node: "A1.4", title: `A1.4 — Routine and outreach immunization, ${M}`, date: day(m, 21), loc: `${s[1]}, Turkana County`, total: v("HL-1.4a"), male: dm, female: df,
     summary: `Facilities and ${v("HL-1.4b")} outreach sessions immunized ${v("HL-1.4a")} children under one year with Penta3 in ${M}; DTP3/Penta3 coverage at supported facilities reached ${v("HL-OC1c")} percent. Cold chain checks were done at every facility.`,
     achievements: `${v("HL-1.4a")} children received DTP3/Penta3 (${df} girls, ${dm} boys) through ${v("HL-1.4b")} outreach sessions in ${M}; coverage ${v("HL-OC1c")} percent.`, challenges: ch, lessons: "Fixed outreach calendars shared with CHVs increase turnout at outreach sessions.", next: m < 5 ? "Continue outreach sessions and monthly cold-chain checks." : "Final cold-chain inventory and handover of outreach schedules to the county." },
   { node: "A1.5", title: `A1.5 — Monthly data review and KHIS data quality audit, ${M}`, date: day(m, 25), loc: "Lodwar, Turkana County", total: 28,
     summary: `Facility in-charges and records officers met for the monthly data review with the sub-county health records officers; data quality audits compared registers with KHIS entries in all 14 facilities. ${v("HL-1.5a")} percent of supported facilities submitted their monthly reports on time.`,
     achievements: `Monthly data review held with 28 participants; ${v("HL-1.5a")} percent of facilities reported on time in ${M}.`, challenges: m === 1 || m === 2 ? "Intermittent internet and power outages delayed uploads at remote facilities." : "Some facilities still enter data late after staff rotations.", lessons: "Printing the reporting-rate dashboard for the review meeting makes late facilities act.", next: m < 5 ? "Continue monthly review; follow up on late-reporting facilities." : "Hand over audit tools to the sub-county records officers." },
   { node: "A2.1", title: `A2.1 — CHV training and kitting, ${M}`, date: day(m, 11), loc: `${s[0]} Community Health Unit, Turkana County`, total: v("HL-2.1a"), male: cm, female: cf,
     summary: `${v("HL-2.1a")} community health volunteers from the Community Health Units attached to supported facilities were trained on the community health package, iCCM, MUAC screening and danger-sign counselling, and received kits (MUAC tapes, ORS and zinc, job aids) in ${M}.`,
     achievements: `${v("HL-2.1a")} CHVs trained and kitted in ${M} (${cf} women, ${cm} men).`, challenges: m === 0 ? "Some CHVs walked more than 15 km to reach the training venue." : m === 2 ? "CHVs in strike-affected sub-counties could not be supervised by facility staff for twelve days." : "A few CHVs missed sessions because of livestock movements and long distances.", lessons: m === 0 ? "Holding training at the nearest facility reduces absenteeism." : "Peer supervision by experienced CHVs keeps newly trained volunteers active.", next: m < 5 ? "Train the next CHV cohort and supervise those already trained." : "Final CHV refresher and handover of the supervision checklist." },
   { node: "A2.2", title: `A2.2 — Community dialogue days and household visits, ${M}`, date: day(m, 16), loc: `${s[1]} catchment area, Turkana County`, total: v("HL-2.2a"), male: rm, female: rf,
     summary: `CHVs and project community mobilisers held community dialogue days, household visits and radio sessions on antenatal care, facility delivery, immunization, child danger signs and nutrition in ${M}, reaching ${v("HL-2.2a")} people.`,
     achievements: `${v("HL-2.2a")} people reached with community health education in ${M} (${rf} women and girls, ${rm} men and boys).` + (v("HL-OC2a") != null ? ` Spot survey: ${v("HL-OC2a")} percent of caregivers could name three child danger signs.` : ""), challenges: ch, lessons: "Dialogues timed to market days and water-point visits reach more men.", next: m < 5 ? "Continue dialogue days and radio messages." : "Hold close-out dialogues with elders and village health committees." },
   { node: "A2.3", title: `A2.3 — MUAC screening and malnutrition referral, ${M}`, date: day(m, 23), loc: `${s[2]} catchment area, Turkana County`, total: v("HL-2.3a"), male: mm, female: mf,
     summary: `CHVs screened ${v("HL-2.3a")} children aged 6 to 59 months with MUAC tapes in ${M} and referred ${v("HL-2.3b")} children with acute malnutrition to CMAM sites.`,
     achievements: `${v("HL-2.3a")} children screened (${mf} girls, ${mm} boys) and ${v("HL-2.3b")} referred to treatment in ${M}.`, challenges: ch, lessons: m >= 4 ? "Screening at water points finds more children than house-to-house visits during drought." : "Screening during routine CHV household visits finds children who would otherwise be missed and keeps referral slips linked to the village register.", next: m < 5 ? "Continue monthly screening and track referral completion." : "Hand over MUAC registers and referral slips to the county nutrition coordinator." },
  ].map(a => ({ ...a, adapt: ch === CH[m + 1]?.[0] ? CH[m + 1][1] : undefined }));
}
export const ADAPT = (m) => (CH[m + 1] ?? CH[1])[1];
