docRoot                   /home/sa.donerdesk.online/html
vhDomain                  sa.donerdesk.online
adminEmails               admin@donerdesk.online
enableGzip                1

index  {
  useServer               0
}

errorlog $VH_ROOT/logs/error.log { useServer 0; logLevel WARN; rollingSize 10M }
accesslog $VH_ROOT/logs/access.log { useServer 0; rollingSize 10M; keepDays 10 }

extProcessor donordesk_superadmin {
  type                    proxy
  address                 127.0.0.1:3012
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context /.well-known/acme-challenge {
  location                /usr/local/lsws/Example/html/.well-known/acme-challenge
  allowBrowse             1
  rewrite  {
    enable                0
  }
  addDefaultCharset       off
}

context / {
  type                    proxy
  handler                 donordesk_superadmin
  addDefaultCharset       off
}

rewrite  {
  enable                  0
}

vhssl {
  keyFile                 /etc/letsencrypt/live/sa.donerdesk.online/privkey.pem
  certFile                /etc/letsencrypt/live/sa.donerdesk.online/fullchain.pem
}
